### ISSUE TITLE
Using library in Objective-C project

### ISSUE THREAD

**Issue by ghost** [solutionarchitectstech/mobile_sdk_demo_ios#1]
Hello, I have a problem, after install library through cocoapods, App project crush with error:
```
Symbol not found: _$s4Moya0A8ProviderCyxG7RxSwift18ReactiveCompatibleAAMc

Referenced from: /Users/a1/Library/Developer/Xcode/DerivedData/Apteka-algtvvwoxoxyrqamgiaaasqhtuox/Build/Products/Debug-iphonesimulator/SATrackingSDK.framework/SATrackingSDK

Expected in: /Users/a1/Library/Developer/CoreSimulator/Devices/38DDA49D-8FF3-4688-996C-C316A106835B/data/Containers/Bundle/Application/885D0596-A9B6-4ECD-9ECA-146DD6947C23/Apteka.app/Frameworks/Moya.framework/Moya
```

How, Can I fix it?

And also when I use SAAdvertisingBannerView in Objective-C project, I can't use BannerView methods loadData and property delegate, they are hidden.

**Comment by fmaxx** [comment]
@armida001 thank you for the feedback. Unfortunately, SDK isn't supported Obj-C. We'll fix that in future releases.

**Comment by ghost** [comment]
But SAAdvertisingBannerView is enable for using, Is only SATrackingSDK not supported?

**Comment by fmaxx** [comment]
> But SAAdvertisingBannerView is enable for using, Is only SATrackingSDK not supported?

Yes right. Currently, SATrackingSDK is not compatible with Obj-C at this moment. We are on top of it. We will keep you posted about status.
